LOAD DATA LOCAL INFILE 'data/students.csv'
INTO TABLE students FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'data/courses.csv'
INTO TABLE courses FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'data/marks.csv'
INTO TABLE marks FIELDS TERMINATED BY ',' IGNORE 1 LINES;
